# Dependabot disabled - using manual dependency management
# Uncomment below if you want to re-enable automated dependency updates

version: 2
updates:
  # npm packages - SECURITY UPDATES ONLY
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'  # Check daily for security issues
      time: '09:00'
      timezone: 'UTC'
    # Limit concurrent PRs
    open-pull-requests-limit: 5
    # ONLY security updates - no feature updates
    allow:
      - dependency-type: 'direct'
        update-types: ['version-update:semver-patch']
      - dependency-type: 'indirect'
        update-types: ['version-update:semver-patch']
    # Only create PRs for security vulnerabilities
    labels:
      - 'security'
      - 'dependencies'
    reviewers:
      - 'marekcaba'
    commit-message:
      prefix: 'security'
      include: 'scope'
    # Group security updates
    groups:
      security-patches:
        patterns:
          - '*'
        update-types:
          - 'security'
  
  # GitHub Actions - security updates only  
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 2
    labels:
      - 'security'
      - 'github-actions'
    commit-message:
      prefix: 'security'
      include: 'scope'

# Manual dependency management for feature updates
# Use: pnpm run deps:check for controlled feature updates
