[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["echo 'Skipping install phase - handled by build script'"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "node dist/apps/backend/main.js" 