packages:

  - apps/*
  - libs/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  koa@<2.16.1: '>=2.16.1'
