packages:
  - apps/*
  - libs/*
auditConfig:
  ignoreGhsas:
    - GHSA-5xrq-8626-4rwp
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  koa@<2.16.1: '>=2.16.1'
  '@fastify/middie@<9.3.2': '>=9.3.2'
  form-data@<4.0.4: '>=4.0.4'
  shell-quote@<1.8.4: '>=1.8.4'
  '@babel/core@>=7.0.0': 7.28.5
patchedDependencies:
  signalsmith-stretch@1.3.2: patches/signalsmith-stretch@1.3.2.patch
