// Re-export all types from their respective modules
export type { MetronomeSettings, TokenInfo, TokenStatus } from './common.js';
export type {
  User,
  AuthUser,
  UserProfile,
  UserPreferences as UserPreferencesBase,
  AuthCredentials,
} from './user.js';
export type { Content, Exercise, ExerciseMetadata } from './content.js';

// Epic 3 & 4 Compatible Exercise Types
export type {
  ExerciseDifficulty,
  TechniqueType,
  ExerciseNote,
  Exercise as DatabaseExercise,
  ExerciseWithNotes,
  CustomBassline,
  GetExercisesResponse,
  GetExerciseResponse,
  GetCustomBasslinesResponse,
  CreateExerciseRequest,
  UpdateExerciseRequest,
  // Story 3.8: Enhanced Bassline Persistence Types
  BasslineMetadata,
  SavedBassline,
  AutoSaveConfig,
  SaveBasslineRequest,
  AutoSaveRequest,
  RenameBasslineRequest,
  DuplicateBasslineRequest,
  BasslineListFilters,
  SavedBasslinesResponse,
  SaveBasslineResponse,
  AutoSaveResponse,
  SharingOptions,
  SharedBassline,
} from './exercise.js';
export { TechniqueTypes } from './exercise.js';

export type {
  Widget,
  WidgetConfiguration,
  YouTubeExercise,
} from './widgets.js';

// Enhanced playback types for comprehensive widget integration
export type {
  // Core playback types
  PlaybackState,
  AudioTrack,
  AudioContextConfig,
  PerformanceMetrics,

  // Epic 2 integration types
  N8nPayloadConfig,
  AssetReference,
  AssetManifest,
  AssetLoadingProgress,

  // Widget configuration types
  WidgetAudioConfig,
  MobileAudioConfig,
  WidgetPlaybackPreferences,
  WidgetPlaybackState,

  // Widget communication types
  WidgetPlaybackEvent,
  WidgetSyncConfig,

  // Error handling types
  PlaybackError,

  // Form and validation types
  WidgetConfigForm,

  // API types
  PlaybackControlRequest,
  PlaybackStateResponse,
  AudioTrackRequest,
  WidgetStateUpdate,

  // Real-time event types
  PlaybackEvent,
  WidgetEvent,
  SystemEvent,
} from './playback.js';

// Story 2.4: Advanced Asset Management & CDN Integration types
export type {
  // Core storage configuration
  SupabaseAssetClientConfig,
  DownloadOptions,
  DownloadResult,
  AssetMetadata,
  StorageMetrics,
  ConnectionHealth,

  // Advanced optimization types
  CDNOptimizationConfig,
  GeographicOptimizationConfig,
  CircuitBreakerConfig,
  AdvancedCacheConfig,
  PredictiveLoadingConfig,
  AssetProcessingConfig,

  // Error handling and monitoring
  StorageError,
  AssetAnalytics,
  BandwidthMonitor,

  // Offline and synchronization
  OfflineStorageConfig,
  AssetSyncStatus,

  // User experience and loading
  LoadingExperienceConfig,
  SmartPrefetchConfig,
  AssetOptimizationResult,
  DeliveryOptimization,

  // Advanced configuration
  StorageProvider,
  AssetRequestConfig,
  RetryConfig,
  CacheRequestConfig,

  // Logging and monitoring
  CircuitBreakerState,

  // Authentication and Security (Story 2.4 Subtask 1.2)
  AuthenticationConfig,
  TokenRefreshConfig,
  SessionManagementConfig,
  SecurityMonitoringConfig,
  SecurityAlertThresholds,
  AuthenticationMetrics,
  SessionState,
  TokenInfo as StorageTokenInfo,
  DeviceInfo,
  LocationInfo,
  AuthenticationError,
  SecurityContext,
  AuthenticationEvent,
  SecurityIncident,

  // Error Handling and Recovery (Story 2.4 Subtask 1.4)
  ErrorRecoveryConfig,
  RetryPolicy,
  RetryBudget,
  EnhancedCircuitBreakerConfig,
  HealthCheckConfig,
  HealthCheckEndpoint,
  CustomHealthCheck,
  ErrorClassification,
  ErrorType,
  ErrorSeverity,
  ErrorCategory,
  RecoveryStrategy,
  RecoveryStrategyType,
  FallbackOption,
  DegradationLevel,
  ErrorAnalytics,
  ErrorPattern,
  RecoveryResult,
  DetailedHealthStatus,
  ComponentHealth,
  HealthTrend,

  // Bucket Management and Organization (Story 2.4 Subtask 1.3)
  BucketManagementConfig,
  BucketInfo,
  BucketCategory,
  BucketPermissions,
  BucketHealthStatus,
  BucketIssue,

  // Asset Versioning System
  VersioningConfig,
  AssetVersion,
  AssetVersionMetadata,
  VersionDiff,
  VersionChange,

  // Metadata Indexing and Search
  MetadataIndexingConfig,
  AssetMetadataIndex,
  ExtractedMetadata,
  AssetRelationship,
  AssetSearchQuery,
  AssetSearchFilters,
  AssetSearchSorting,
  SearchPagination,
  AssetSearchResult,
  SearchFacet,
  FacetValue,

  // Automated Cleanup System
  AutomatedCleanupConfig,
  CleanupSchedule,
  RetentionPolicy,
  RetentionCondition,
  RetentionAction,
  OrphanedAssetCleanupConfig,
  DuplicateDetectionConfig,
  StorageOptimizationConfig,
  ArchivalConfig,
  CleanupNotificationConfig,
  CleanupResult,
  CleanupError,

  // Bucket Analytics and Insights
  BucketAnalytics,
  AnalyticsPeriod,
  StorageUsageAnalytics,
  DataPoint,
  CategoryUsage,
  AssetSizeInfo,
  AccessPatternAnalytics,
  PopularAssetInfo,
  UserAccessPattern,
  BucketPerformanceMetrics,
  SlowOperationInfo,
  StorageCostAnalytics,
  CategoryCost,
  BucketRecommendation,

  // Extended Storage Types
  BucketAuditLog,
  BucketOperation,

  // Advanced Multi-Level Caching System (Story 2.4 Task 6)
  AdvancedCacheManagerConfig,
  AdvancedCacheEntry,
  CacheLayerDistribution,
  AccessPrediction,
  CachePredictionFactor,
  LayerPrediction,
  CompressionBenefit,
  CompressionFactor,
  IntelligentCompressionConfig,
  AudioCompressionConfig,
  MIDICompressionConfig,
  MetadataCompressionConfig,
  CacheSyncStatus,
  SyncOperation,
  CompressionResult,
  CompressionStrategy,
  CompressionQualityAssessment,
  CompressionOperationResult,
  CompressionAnalytics,
  CompressionPreset,
  CompressionProfile,
  NetworkAdaptiveConfig,
  QualityMetrics,

  // Cache Synchronization Types (Story 2.4 Subtask 6.5)
  CacheLayerConfig,
  CacheEntry,
  CacheMetadata,
  SynchronizationResult,
  SyncOperationResult,
  SynchronizationEvent,
  ConflictInfo,
  ConflictResolutionResult,
  MergeStrategy,
  SyncAnalytics,
  CrossLayerSyncConfig,
  SyncState,
  LayerSyncStatus,
  SyncPerformanceMetrics,
  ConflictType,
  ResolutionStrategy,
  SyncEventType,
  SyncPriority,
  SynchronizationStrategy,
  CacheSynchronizationConfig,
  CacheConflictResolution,
  CacheSyncConflict,
  AdvancedCacheOperationResult,
  AdvancedCacheAnalytics,
  CacheOptimizationSuggestion,
  CacheLayer,
  CacheOptimizationCategory,
  CacheAnalyticsConfig,
  CachePerformanceThresholds,

  // Story 2.4 Task 5: MIDI Orchestration System
  MIDIAssetOrchestratorConfig,
  MIDIMetadata,
  MIDIOperationResult,
  MIDIVersionInfo,
  MIDICollaborator,
  MIDIAnalyticsData,
  MIDIRealtimeUpdate,
  MIDIConflictInfo,
  MIDIValidationResult,
  MIDIFormat,
  MIDIType,
  MIDITrackType,
  MIDITrackInfo,
  MIDIChannelInfo,
  MIDIInstrument,
  MIDIInstrumentCategory,
  MIDIComplexityAnalysis,
  MIDIComplexityFactor,
  MIDIHarmonicAnalysis,
  MIDIChord,
  MIDIModulation,
  MIDIRhythmicAnalysis,
  MIDIRhythmicPattern,
  MIDIGroove,
  MIDINoteRange,
  MIDIVelocityInfo,
  MIDITempoChange,
  MIDITimeSignatureChange,
  MIDIKeySignatureChange,
  MIDIVersionControlConfig,
  MIDIConflictResolutionStrategy,
  MIDIVersionChange,
  MIDIMusicalImpact,
  MIDIVersionDiff,
  MIDICollaborativeConfig,
  MIDIPermissionLevel,
  MIDIContribution,
  MIDICollaboratorPreferences,
  MIDIRealTimeSyncConfig,
  MIDIUpdateType,
  MIDIOperation,
  MIDIMetadataProcessingConfig,
  MIDITaggingStrategy,
  MIDIValidationRule,

  // Audio Analysis Types (Story 2.4 Task 4.2)
  AudioMetadata,
  AnalysisConfig,
  TempoDetectionResult,
  KeyDetectionResult,
  SpectralAnalysisResult,
  QualityAssessmentResult,
  MusicalFeatures,
  FrequencyBinData,
  HarmonicContent,
  OnsetDetectionResult,
  AnalysisResult as AudioAnalysisResult,
} from './storage.js';

export type { LearningProgress } from './learning.js';
export type { AnalysisResult, AudioAnalysis, AudioNote } from './analysis.js';

// Story 2.4 Subtask 1.5: Real-time Health Monitoring & Performance Analytics
export type {
  RealTimeMonitoringConfig,
  HealthMonitoringConfig,
  ComponentMonitoringConfig,
  HealthThresholdConfig,
  PerformanceAnalyticsConfig,
  PerformanceTrend,
  PerformanceDataPoint,
  SeasonalPattern,
  PerformanceAnomaly,
  AnomalyContext,
  PerformancePrediction,
  PredictedValue,
  PredictionFactor,
  AlertingConfig,
  AlertRule,
  AlertCondition,
  AlertThreshold,
  AlertNotification,
  AlertDetails,
  AlertAcknowledgment,
  AlertChannel,
  AlertChannelConfig,
  RateLimitConfig,
  NotificationRetryPolicy,
  AlertFilterRule,
  EscalationPolicy,
  EscalationLevel,
  EscalationCondition,
  AlertGroupingConfig,
  AlertSuppressionRule,
  MaintenanceWindow,
  RecurrencePattern,
  HealthDashboard,
  DashboardLayout,
  LayoutBreakpoint,
  WidgetSize,
  HealthWidget,
  WidgetType,
  WidgetPosition,
  TimeRange,
  WidgetThreshold,
  WidgetDataSource,
  WidgetPermissions,
  DashboardPermissions,
  DashboardFilter,
  FilterOption,
  HealthReport,
  OverallHealthStatus,
  ComponentHealthReport,
  ComponentIssue,
  ComponentMetrics,
  PerformanceSummary,
  PerformanceTrendSummary,
  PerformanceBottleneck,
  AlertSummary,
  TopAlertRule,
  HealthRecommendation,
  HealthTrendSummary,
  IncidentSummary,
  CustomReportSection,
  ReportChart,
  ChartDataPoint,
  ChartConfiguration,
  HealthInsight,
  InsightEvidence,
  MonitoringIntegration,
  MonitoringIntegrationConfig,
  AuthConfig,
  OAuth2Config,
  MetricsExportConfig,
  ExportRetryPolicy,
  MetricsFilterRule,
  MetricsTransformationRule,
  HealthWebhook,
  HealthWebhookEvent,
  WebhookRetryPolicy,
  RealTimeMonitoringEvent,
  RealTimeEventType,
  MonitoringSession,
  MonitoringSubscription,
  SessionFilter,

  // Story 2.4 Task 2: Global CDN Optimization System
  CDNOptimizationConfig as CDNOptimizationConfigV2,
  CDNProvider,
  CDNEdgeConfig,
  GeographicDistributionConfig as CDNGeographicDistributionConfig,
  EdgeSelectionStrategy,
  EdgeSelectionCriteria,
  GeographicLoadBalancingConfig,
  GeographicFailoverStrategy,
  EdgeLocation,
  EdgeFeature,
  EdgeRoutingStrategy,
  RoutingWeights,
  RoutingRule,
  LoadBalancingConfig,
  LoadBalancingRetryPolicy,
  EdgeHealthCheckConfig,
  CustomEdgeHealthCheck,
  EdgeFailoverConfig,
  EdgeCachingStrategy,
  CacheRule,
  CachePurgeStrategy,
  ContentOptimizationConfig,
  ImageOptimizationConfig,
  AudioOptimizationConfig,
  QualityLevel,
  AudioQualityLevel,
  CompressionConfig,
  FormatConversionConfig,
  ImageConversionRule,
  AudioConversionRule,
  BandwidthAdaptationConfig,
  NetworkDetectionConfig,
  BandwidthAdaptationRule,
  NetworkCondition,
  BufferManagementConfig,
  QualityAdaptationConfig,
  DeviceDetectionConfig,
  UserPreferenceConfig,
  QualityAdaptationRule,
  AdaptationCondition,
  AdaptiveStreamingConfig,
  StreamingQualityLevel,
  BitrateAdaptationConfig,
  StreamingBufferConfig,
  StreamingFallbackConfig,
  CDNPerformanceMonitoringConfig,
  CDNMetricsCollectionConfig,
  CDNMetricType,
  CustomCDNMetric,
  CDNPerformanceThresholds,
  CDNAlertingConfig,
  CDNAlertRule,
  CDNAlertSuppressionRule,
  CDNReportingConfig,
  CDNReportType,
  ReportSchedule,
  CustomCDNReport,
  CDNRealTimeMonitoringConfig,
  CDNAnalyticsConfig,
  CDNDataCollectionConfig,
  CDNAnalysisConfig,
  CDNOptimizationAnalysisConfig,
  CDNAnalyticsReportingConfig,
  CDNAnalyticsIntegrationConfig,
  GoogleAnalyticsIntegration,
  DatadogIntegration,
  NewRelicIntegration,
  CustomAnalyticsIntegration,
  CDNFallbackStrategy,
  CDNFallbackOption,
  CDNPerformanceMetrics,
  EdgePerformanceMetric,
  GeographicMetric,
  CDNOptimizationRecommendation,
  OptimizationImpact,
  OptimizationImplementation,
  OptimizationMetrics,
  CDNHealthStatus,
  CDNComponentHealth,
  EdgeLocationHealth,
  CDNHealthIssue,

  // Story 2.4 Task 3: Predictive Asset Loading Engine
  PredictiveLoadingEngineConfig,
  MachineLearningConfig,
  ModelTrainingConfig,
  FeatureEngineeringConfig,
  BehaviorAnalysisConfig,
  IntelligentPrefetchingConfig,
  PredictiveModelConfig,
  AdaptiveLearningConfig,
  PredictivePerformanceConfig,
  AnalyticsIntegrationConfig,
  AssetPrediction,
  UserBehaviorProfile,
  PracticePattern,
  AssetUsagePattern,
  LearningEvent,
  PrefetchRequest,
  PrefetchResult,
  PrefetchResourceUsage,
  PrefetchPerformance,
  ConfusionMatrix,
  TrainingHistoryEntry,
  AdaptationHistoryEntry,
  ModelPersistenceConfig,
  PredictionThresholds,
  CrossValidationConfig,
  ExerciseProgressionModelConfig,
  AssetDemandModelConfig,
  UserIntentModelConfig,
  SessionLengthModelConfig,
  SkillDevelopmentModelConfig,
  ModelEnsembleConfig,
  FeedbackLoopConfig,
  ModelUpdateStrategy,
  OnlineLearningConfig,
  TransferLearningConfig,
  ContinuousImprovementConfig,
  AdaptivePerformanceThresholds,
  AccuracyMetricsConfig,
  LatencyRequirementsConfig,
  ResourceLimitsConfig,
  OptimizationTargetsConfig,
  PredictiveMonitoringConfig,
  BehaviorPatternIntegrationConfig,
  PracticeSessionIntegrationConfig,
  ProgressAnalysisIntegrationConfig,
  DataExchangeProtocolConfig,

  // Core prediction types and enums
  PredictionPriority,
  PracticePatternType,
  AssetType,
  LearningEventType,
  PatternType,
  FeedbackSource,
  ModelUpdateTrigger,

  // Supporting interfaces
  PredictionContext,
  PredictionTrigger,
  PredictionMetadata,
  LearningCharacteristics,
  UserPreferences,
  SkillProgression,
  SessionCharacteristics,
  PredictiveMetrics,
  AssetAccessSequence,
  ContextualUsage,
  SeasonalTrend,
  CorrelatedAsset,
  LearningEventContext,
  LearningEventAsset,
  LearningOutcome,
  LearningEventFeatures,
  LearningEventLabels,
  PrefetchResourceLimits,
  PrefetchValidationRule,
  PrefetchRequestMetadata,
  PrefetchAssetResult,

  // Extended supporting interfaces
  TimeOfDayPattern,
  DurationPattern,
  IntensityPattern,
  AssetPreferencePattern,
  ProgressionStylePattern,
  PlateauIndicator,
  BreakPattern,
  IntensityProfile,
  FocusPattern,
  PredictionHistoryEntry,
  PrioritizationWeights,
  ResourceAllocationStrategy,
  QuotaManagementConfig,
  ThrottlingConfig,
  NetworkQualityThresholds,
  NetworkQualityRange,
  BackgroundLimits,
  ValidationRule,
  ExpirationHandlingStrategy,
  ModelRetentionPolicy,
  ActionThreshold,
  ContextualThreshold,
  ExerciseProgressionFeatures,
  AssetDemandFeatures,
  UserIntentFeatures,
  IntentCategory,
  SessionLengthFeatures,
  SkillDevelopmentFeatures,
  MasteryThreshold,
  PerformanceThreshold,
  ResourceThreshold,
  AdaptationTrigger,
  DegradationThreshold,
  AccuracyMetric,
  AccuracyAlertThreshold,
  RetrainingTrigger,
  OptimizationConstraint,
  FeedbackAggregationStrategy,
  FeedbackWeightingConfig,
  RewardSignalConfig,
  RewardSignal,
  PenaltySignalConfig,
  PenaltySignal,
  FeedbackValidationConfig,
  UpdateFrequency,
  RollbackStrategy,
  RollbackCriteria,
  ModelVersionControl,
  SourceModelConfig,
  ImprovementMetric,
  ExperimentationConfig,
  ExperimentType,
  ABTestingConfig,
  PerformanceBaselineConfig,

  // Additional Task 3 interfaces
  UserSegment,
  SegmentCriteria,
  SegmentCharacteristics,
  CorrelationMatrix,
  PrefetchStrategy,
  PrefetchStrategyParameters,
  PrefetchCondition,
  PredictiveModelsConfig,
  PerformanceOptimizationConfig,
  ModelPerformanceMetrics,
  AdaptiveLearningMetrics,

  // Story 2.4 Task 4: Professional Audio Sample Management
  AudioSampleManagerConfig,
  AudioSampleMetadata,
  AudioSampleFormat,
  AudioSampleQualityProfile,
  AudioSampleCategory,
  AudioSampleOperationResult,
  AudioSampleLibrary,
  AudioSampleLibraryConfig,
  AudioSampleLibraryStatistics,
  AudioSampleQualityThresholds,
  SampleCacheEntry,
  SampleAnalyticsData,
  SampleAnalyticsConfig,
  SampleQualityThresholds,
  SamplePerformanceThresholds,
  SampleAlertThresholds,
  SamplePlaybackMetrics,
  SampleQualityMetrics,
  SamplePerformanceMetrics,
  SampleUsageMetrics,
  SampleInteractionMetrics,
  AdaptiveAudioStreamingConfig,
  IntelligentSampleCacheConfig,
  BandwidthThresholds,
  LatencyThresholds,
} from './storage.js';
