// Re-export all types from their respective modules
export type { MetronomeSettings, TokenInfo, TokenStatus } from './common.js';

// API Data Transfer Objects (shared between frontend domains)
export type {
  ExerciseDTO,
  TutorialDTO,
  TutorialLevelType,
  TutorialStatusType,
  TutorialSectionDTO,
  TutorialListResponseDTO,
  TutorialWithExercisesResponseDTO,
  SaveWithExercisesResponseDTO,
  PaginatedResponseDTO,
} from './api-dto.js';
export type {
  User,
  AuthUser,
  UserProfile,
  UserPreferences as UserPreferencesBase,
  BassConfiguration,
  AuthCredentials,
  LearningStyle,
} from './user.js';
// Content management types (high-level metadata)
export type { Content, ContentExercise, ExerciseMetadata } from './content.js';
export type {
  Tutorial,
  TutorialWithExercises,
  TutorialSummary,
  TutorialsResponse,
  TutorialResponse,
  TutorialExercisesResponse,
  CreateTutorialDto,
  UpdateTutorialDto,
  // Act 1: Understand types
  UnderstandQuestion,
  UnderstandQuestionOption,
} from './tutorial.js';

// Musical exercise types (detailed exercise data with notes, timing, etc.)
export type {
  ExerciseDifficulty,
  TechniqueType,
  ExerciseNote,
  Exercise as MusicalExercise, // Full musical exercise with notes and timing
  ExerciseWithNotes,
  CustomBassline,
  GetExercisesResponse,
  GetExerciseResponse,
  GetCustomBasslinesResponse,
  CreateExerciseRequest,
  UpdateExerciseRequest,
  // Multi-track data architecture types
  TrackConfiguration,
  DrumPattern,
  HarmonyVoicing,
  HarmonyControlChange, // MIDI control change events for harmony instruments
  // Fretboard view configuration types
  FretboardViewPreset,
  FretboardScrollMode,
  FretboardViewConfig,
  // Story 3.8: Enhanced Bassline Persistence Types
  BasslineMetadata,
  SavedBassline,
  AutoSaveConfig,
  SaveBasslineRequest,
  AutoSaveRequest,
  RenameBasslineRequest,
  DuplicateBasslineRequest,
  BasslineListFilters,
  SavedBasslinesResponse,
  SaveBasslineResponse,
  AutoSaveResponse,
  SharingOptions,
  SharedBassline,
} from './exercise.js';
export { TechniqueTypes } from './exercise.js';

export type {
  Widget,
  WidgetConfiguration,
  YouTubeExercise,
} from './widgets.js';

// Enhanced playback types for comprehensive widget integration
export type {
  // Core playback types
  PlaybackState,
  AudioTrack,
  AudioContextConfig,
  PerformanceMetrics,

  // Epic 2 integration types
  N8nPayloadConfig,
  AssetReference,
  AssetManifest,
  AssetLoadingProgress,

  // Widget configuration types
  WidgetAudioConfig,
  MobileAudioConfig,
  WidgetPlaybackPreferences,
  WidgetPlaybackState,

  // Widget communication types
  WidgetPlaybackEvent,
  WidgetSyncConfig,

  // Error handling types
  PlaybackError,

  // Form and validation types
  WidgetConfigForm,

  // API types
  PlaybackControlRequest,
  PlaybackStateResponse,
  AudioTrackRequest,
  WidgetStateUpdate,

  // Real-time event types
  PlaybackEvent,
  WidgetEvent,
  SystemEvent,
} from './playback.js';

// Story 2.4: Advanced Asset Management & CDN Integration types
// Re-exported from modular storage types
export type {
  // Core storage configuration
  SupabaseAssetClientConfig,
  DownloadOptions,
  DownloadResult,
  AssetMetadata,
  StorageMetrics,
  ConnectionHealth,

  // Advanced optimization types
  CDNOptimizationConfig,
  GeographicOptimizationConfig,
  CircuitBreakerConfig,
  AdvancedCacheConfig,
  PredictiveLoadingConfig,
  AssetProcessingConfig,

  // Error handling and monitoring
  StorageError,
  AssetAnalytics,
  BandwidthMonitor,

  // Offline and synchronization
  OfflineStorageConfig,
  AssetSyncStatus,

  // User experience and loading
  LoadingExperienceConfig,
  SmartPrefetchConfig,
  AssetOptimizationResult,
  DeliveryOptimization,

  // Advanced configuration
  StorageProvider,
  AssetRequestConfig,
  RetryConfig,
  CacheRequestConfig,

  // Logging and monitoring
  CircuitBreakerState,

  // Authentication and Security (Story 2.4 Subtask 1.2)
  AuthenticationConfig,
  TokenRefreshConfig,
  SessionManagementConfig,
  SecurityMonitoringConfig,
  SecurityAlertThresholds,
  AuthenticationMetrics,
  SessionState,
  TokenInfo as StorageTokenInfo,
  DeviceInfo,
  LocationInfo,
  AuthenticationError,
  SecurityContext,
  AuthenticationEvent,
  SecurityIncident,

  // Error Handling and Recovery (Story 2.4 Subtask 1.4)
  ErrorRecoveryConfig,
  RetryPolicy,
  RetryBudget,
  EnhancedCircuitBreakerConfig,
  HealthCheckConfig,
  HealthCheckEndpoint,
  CustomHealthCheck,
  ErrorClassification,
  ErrorType,
  ErrorSeverity,
  ErrorCategory,
  RecoveryStrategy,
  RecoveryStrategyType,
  FallbackOption,
  DegradationLevel,
  ErrorAnalytics,
  ErrorPattern,
  RecoveryResult,
  DetailedHealthStatus,
  ComponentHealth,
  HealthTrend,

  // Bucket Management and Organization (Story 2.4 Subtask 1.3)
  BucketManagementConfig,
  BucketInfo,
  BucketCategory,
  BucketPermissions,
  BucketHealthStatus,
  BucketIssue,

  // Asset Versioning System
  VersioningConfig,
  AssetVersion,
  AssetVersionMetadata,
  VersionDiff,
  VersionChange,

  // Metadata Indexing and Search
  MetadataIndexingConfig,
  AssetMetadataIndex,
  ExtractedMetadata,
  AssetRelationship,
  AssetSearchQuery,
  AssetSearchFilters,
  AssetSearchSorting,
  SearchPagination,
  AssetSearchResult,
  SearchFacet,
  FacetValue,

  // Automated Cleanup System
  AutomatedCleanupConfig,
  CleanupSchedule,
  RetentionPolicy,
  RetentionCondition,
  RetentionAction,
  OrphanedAssetCleanupConfig,
  DuplicateDetectionConfig,
  StorageOptimizationConfig,
  ArchivalConfig,
  CleanupNotificationConfig,
  CleanupResult,
  CleanupError,

  // Bucket Analytics and Insights
  BucketAnalytics,
  AnalyticsPeriod,
  StorageUsageAnalytics,
  DataPoint,
  CategoryUsage,
  AssetSizeInfo,
  AccessPatternAnalytics,
  PopularAssetInfo,
  UserAccessPattern,
  BucketPerformanceMetrics,
  SlowOperationInfo,
  StorageCostAnalytics,
  CategoryCost,
  BucketRecommendation,

  // Extended Storage Types
  BucketAuditLog,
  BucketOperation,

  // Advanced Multi-Level Caching System (Story 2.4 Task 6)
  AdvancedCacheManagerConfig,
  AdvancedCacheEntry,
  CacheLayerDistribution,
  AccessPrediction,
  CachePredictionFactor,
  LayerPrediction,
  CompressionBenefit,
  CompressionFactor,
  IntelligentCompressionConfig,
  AudioCompressionConfig,
  MIDICompressionConfig,
  MetadataCompressionConfig,
  CacheSyncStatus,
  SyncOperation,
  CompressionResult,
  CompressionStrategy,
  CompressionQualityAssessment,
  CompressionOperationResult,
  CompressionAnalytics,
  CompressionPreset,
  CompressionProfile,
  NetworkAdaptiveConfig,

  // Cache Synchronization Types (Story 2.4 Subtask 6.5)
  CacheLayerConfig,
  CacheEntry,
  CacheMetadata,
  SynchronizationResult,
  SyncOperationResult,
  SynchronizationEvent,
  ConflictInfo,
  ConflictResolutionResult,
  MergeStrategy,
  SyncAnalytics,
  CrossLayerSyncConfig,
  SyncState,
  LayerSyncStatus,
  SyncPerformanceMetrics,
  ConflictType,
  ResolutionStrategy,
  SyncEventType,
  SyncPriority,
  SynchronizationStrategy,
  CacheSynchronizationConfig,
  CacheConflictResolution,
  CacheSyncConflict,
  AdvancedCacheOperationResult,
  AdvancedCacheAnalytics,
  CacheOptimizationSuggestion,
  CacheLayer,
  CacheOptimizationCategory,
  CacheAnalyticsConfig,
  CachePerformanceThresholds,

  // Story 2.4 Task 5: MIDI Orchestration System
  MIDIAssetOrchestratorConfig,
  MIDIMetadata,
  MIDIOperationResult,
  MIDIVersionInfo,
  MIDICollaborator,
  MIDIAnalyticsData,
  MIDIRealtimeUpdate,
  MIDIConflictInfo,
  MIDIValidationResult,
  MIDIFormat,
  MIDIType,
  MIDITrackType,
  MIDITrackInfo,
  MIDIChannelInfo,
  MIDIInstrument,
  MIDIInstrumentCategory,
  MIDIComplexityAnalysis,
  MIDIComplexityFactor,
  MIDIHarmonicAnalysis,
  MIDIChord,
  MIDIModulation,
  MIDIRhythmicAnalysis,
  MIDIRhythmicPattern,
  MIDIGroove,
  MIDINoteRange,
  MIDIVelocityInfo,
  MIDITempoChange,
  MIDITimeSignatureChange,
  MIDIKeySignatureChange,
  MIDIVersionControlConfig,
  MIDIConflictResolutionStrategy,
  MIDIVersionChange,
  MIDIMusicalImpact,
  MIDIVersionDiff,
  MIDICollaborativeConfig,
  MIDIPermissionLevel,
  MIDIContribution,
  MIDICollaboratorPreferences,
  MIDIRealTimeSyncConfig,
  MIDIUpdateType,
  MIDIOperation,
  MIDIMetadataProcessingConfig,
  MIDITaggingStrategy,
  MIDIValidationRule,

  // Audio Analysis Types (Story 2.4 Task 4.2)
  AudioMetadata,
  AnalysisConfig,
  TempoDetectionResult,
  KeyDetectionResult,
  SpectralAnalysisResult,
  QualityAssessmentResult,
  MusicalFeatures,
  FrequencyBinData,
  HarmonicContent,
  OnsetDetectionResult,
  AnalysisResult as AudioAnalysisResult,
} from './storage/index.js';

export type { LearningProgress } from './learning.js';

// Funnel analytics — event log + anonymous identity types
export type {
  FunnelEventName,
  FunnelEventInput,
  FunnelEvent,
  IdentityLink,
} from './analytics.js';
export { funnelEventNames } from './analytics.js';

// Groove library — reusable groove cards referenced by tutorial/drill blocks
export type {
  GrooveLibraryItem,
  CreateGrooveInput,
  UpdateGrooveInput,
  GrooveLibraryResponse,
} from './grooves.js';

// Assessment types (entrance quiz)
export type {
  // Legacy assessment types (V1 - single video)
  SkillLevel,
  PrimaryGoal,
  BassTechnique as AssessmentBassTechnique,
  MusicGenre,
  QuestionType,
  QuestionOption,
  DragDropConfig,
  TextInputConfig,
  AssessmentQuestion,
  QuizAnswer,
  AssessmentResult,
  AssessmentStatus,
  CompleteAssessmentRequest,
  CompleteAssessmentResponse,
  GetAssessmentStatusResponse,
  AssessmentConfig,
  AssessmentProgress,
  AudioConfig,

  // Segment-based assessment types (V2 - branching flow)
  SkillBucket,
  SegmentTopic,
  VideoSegment,
  FlowNodeType,
  EdgeConditionType,
  FlowNode,
  EdgeConditionValue,
  FlowEdge,
  AssessmentFlowGraph,
  SegmentQuestionType,
  SegmentQuestionCategory,
  SegmentQuestionOption,
  SkillVerificationConfig,
  SegmentQuestion,
  CoachInsightTemplate,
  SessionStatus,
  AssessmentSession,
  AssessmentSessionState,
  SegmentAssessmentResult,
  CreateSessionRequest,
  CreateSessionResponse,
  UpdateSessionRequest,
  MatchInsightRequest,
  MatchInsightResponse,
  CompleteSegmentAssessmentRequest,
  CompleteSegmentAssessmentResponse,
} from './assessment.js';

// Learning journey types
export type {
  JourneyStatus,
  JourneyMilestone,
  MilestoneUnlockCriteria,
  LearningJourney,
  UserJourney,
  UserJourneyWithDetails,
  JourneyProgress,
  GetUserJourneyResponse,
  GetAvailableJourneysResponse,
  AssignJourneyRequest,
  AssignJourneyResponse,
  UpdateJourneyProgressRequest,
  UpdateJourneyProgressResponse,
  JourneyMatchScore,
  JourneyMatchResult,
} from './journey.js';

// Progress system types — block + exercise progress responses
export type {
  BlockProgressEntry,
  ExerciseProgressEntry,
  GetTutorialProgressResponse,
  TutorialCompletionSummary,
  GetUserTutorialCompletionsResponse,
  GetPracticeStreakResponse,
} from './progress.js';

// Block-based tutorial system types
export type {
  BlockType,
  VideoOverlayType,
  // Video overlay event types
  QuizOverlayContent,
  PrepOverlayContent,
  RecordOverlayContent,
  ListenOverlayContent,
  UploadOverlayContent,
  ReflectOverlayContent,
  OverlayContentMap,
  VideoOverlayEvent,
  AnyVideoOverlayEvent,
  // Block config types
  VideoBlockConfig,
  ExerciseBlockConfig,
  GrooveBlockConfig,
  TextBlockConfig,
  CelebrationBlockConfig,
  ExplainMediaType,
  ExplainMediaItem,
  ExplainSlide,
  ExplainBlockConfig,
  BlockConfigMap,
  TutorialBlock,
  VideoBlock,
  ExerciseBlock,
  GrooveBlock,
  GrooveCardBlock,
  GrooveCardBlockConfig,
  ReferenceDropConfig,
  GradingMode,
  ReferenceOnsetPreset,
  ReferenceAnalysis,
  GrooveCardStemSet,
  BasslineVariant,
  ChordChartEntry,
  ChordChart,
  GrooveCardStateCaptions,
  GrooveBrickRole,
  MasteryTier,
  DrillCriterionType,
  DrillCompletionCriterion,
  DrillCompletionResult,
  DrillCompletionData,
  TaskBlockConfig,
  TextBlock,
  CelebrationBlock,
  ExplainBlock,
  TaskBlock,
  AnyBlock,
  BlockProgress,
} from './block.js';

// Bass Gym Training Engine types (Phase 0)
export type {
  GoalType,
  LadderLevel,
  EnrollmentStatus,
  RepResultOutcome,
  ProgressSignal,
  ProgressSignalKind,
  PrereqThreshold,
  GoalTarget,
  BlockRef,
  Stage,
  Topic,
  TopicProgress,
  Goal,
  AdminGoalSummary,
  EnrollableGoal,
  CreateGoalInput,
  UpdateGoalInput,
  GoalSnapshot,
  GoalEnrollment,
  GraduationDoor,
  GraduationSummary,
  MonthInReview,
  ConqueredGroove,
  RepResult,
  ClimbState,
  StudentState,
  StudentSignals,
  StudentAttendance,
  SiblingGoalSummary,
  UserMilestone,
  BlockPool,
  GenerateRep,
  GenerateRepOptions,
  ProgressSignalSource,
  RepResultSink,
  RepResultInput,
} from './training.js';

// Value export (pure mapper, not a type) — drill completion → ProgressSignal.
export { drillCompletionToSignal } from './training.js';

// Value export (const, not a type) — eighth-note slots per bar for chord charts.
export { CHORD_SLOTS_PER_BAR, REFERENCE_MAIN_BASS_KEY } from './block.js';

// Feature registry (LAUNCH-06 product-aware feature entitlement)
export type { FeatureKey } from './features.js';
export { FEATURE_KEYS, isFeatureKey } from './features.js';

// Billing / entitlement types (LAUNCH-02.5c stub; LAUNCH-06 populates caps from grants)
export type {
  EntitlementTier,
  LeverCap,
  LeverCaps,
  EntitlementResponse,
} from './billing.js';

// Pattern Library types (drum pattern library feature)
export type {
  PatternTimeSignature,
  PatternEvent,
  PatternMidiData,
  PatternGenre,
  PatternDifficulty,
  PatternLibraryItem,
  PatternLibraryFilter,
  PatternLibraryResponse,
  PatternLibraryItemResponse,
  CreatePatternInput,
} from './pattern-library.js';
export { GENRE_DISPLAY_NAMES, GENRE_COLORS } from './pattern-library.js';
export type { AnalysisResult, AudioAnalysis, AudioNote } from './analysis.js';

// MusicXML types for sheet music import
export type {
  MusicXMLDocument,
  MusicXMLMetadata,
  MusicXMLNoteData,
  MusicXMLConversionResult,
  MusicXMLConversionConfig,
  BassString,
  Note as MusicXMLNote,
  Pitch as MusicXMLPitch,
  Technical,
  Articulations,
  ScorePartwise,
  Part,
  Measure,
  Attributes,
  Time,
  Key,
} from './musicxml.js';
export { BASS_TUNINGS, DEFAULT_CONVERSION_CONFIG } from './musicxml.js';

// Musical timing types
export type {
  NoteDuration,
  MusicalPosition,
  TimeSignature,
  SwingConfig,
  MusicalTimingConfig,
  Articulation,
  Dynamic,
  RestDuration,
  NoteTimingInfo,
} from './musical-timing.js';
export {
  DURATION_BEAT_VALUES,
  COMMON_TIME_SIGNATURES,
  isValidPosition,
  getNextPosition,
} from './musical-timing.js';

// Bass articulation types
export type {
  BassTechnique,
  BassArticulationType,
  BassArticulation,
  GeneratedBassNote,
  ArticulationMatrixEntry,
  ArticulationSuggestion,
} from './bass-articulation.js';

// Musical timing utilities
// export { MusicalTimeConverter } from '../utils/musical-time-converter.js'; // Moved to services
export { ExerciseMigration } from '../utils/exercise-migration.js';

// Story 2.4 Subtask 1.5: Real-time Health Monitoring & Performance Analytics
export type {
  RealTimeMonitoringConfig,
  HealthMonitoringConfig,
  ComponentMonitoringConfig,
  HealthThresholdConfig,
  PerformanceAnalyticsConfig,
  PerformanceTrend,
  PerformanceDataPoint,
  SeasonalPattern,
  PerformanceAnomaly,
  AnomalyContext,
  PerformancePrediction,
  PredictedValue,
  PredictionFactor,
  AlertingConfig,
  AlertRule,
  AlertCondition,
  AlertThreshold,
  AlertNotification,
  AlertDetails,
  AlertAcknowledgment,
  AlertChannel,
  AlertChannelConfig,
  RateLimitConfig,
  NotificationRetryPolicy,
  AlertFilterRule,
  EscalationPolicy,
  EscalationLevel,
  EscalationCondition,
  AlertGroupingConfig,
  AlertSuppressionRule,
  MaintenanceWindow,
  RecurrencePattern,
  HealthDashboard,
  DashboardLayout,
  LayoutBreakpoint,
  WidgetSize,
  HealthWidget,
  WidgetType,
  WidgetPosition,
  TimeRange,
  WidgetThreshold,
  WidgetDataSource,
  WidgetPermissions,
  DashboardPermissions,
  DashboardFilter,
  FilterOption,
  HealthReport,
  OverallHealthStatus,
  ComponentHealthReport,
  ComponentIssue,
  ComponentMetrics,
  PerformanceSummary,
  PerformanceTrendSummary,
  PerformanceBottleneck,
  AlertSummary,
  TopAlertRule,
  HealthRecommendation,
  HealthTrendSummary,
  IncidentSummary,
  CustomReportSection,
  ReportChart,
  ChartDataPoint,
  ChartConfiguration,
  HealthInsight,
  InsightEvidence,
  MonitoringIntegration,
  MonitoringIntegrationConfig,
  AuthConfig,
  OAuth2Config,
  MetricsExportConfig,
  ExportRetryPolicy,
  MetricsFilterRule,
  MetricsTransformationRule,
  HealthWebhook,
  HealthWebhookEvent,
  WebhookRetryPolicy,
  RealTimeMonitoringEvent,
  RealTimeEventType,
  MonitoringSession,
  MonitoringSubscription,
  SessionFilter,

  // Story 2.4 Task 2: Global CDN Optimization System
  CDNOptimizationConfig as CDNOptimizationConfigV2,
  CDNProvider,
  CDNEdgeConfig,
  GeographicDistributionConfig as CDNGeographicDistributionConfig,
  EdgeSelectionStrategy,
  EdgeSelectionCriteria,
  GeographicLoadBalancingConfig,
  GeographicFailoverStrategy,
  EdgeLocation,
  EdgeFeature,
  EdgeRoutingStrategy,
  RoutingWeights,
  RoutingRule,
  LoadBalancingConfig,
  LoadBalancingRetryPolicy,
  EdgeHealthCheckConfig,
  CustomEdgeHealthCheck,
  EdgeFailoverConfig,
  EdgeCachingStrategy,
  CacheRule,
  CachePurgeStrategy,
  ContentOptimizationConfig,
  ImageOptimizationConfig,
  AudioOptimizationConfig,
  QualityLevel,
  AudioQualityLevel,
  CompressionConfig,
  FormatConversionConfig,
  ImageConversionRule,
  AudioConversionRule,
  BandwidthAdaptationConfig,
  NetworkDetectionConfig,
  BandwidthAdaptationRule,
  CDNNetworkCondition as NetworkCondition,
  BufferManagementConfig,
  QualityAdaptationConfig,
  DeviceDetectionConfig,
  UserPreferenceConfig,
  QualityAdaptationRule,
  AdaptationCondition,
  AdaptiveStreamingConfig,
  StreamingQualityLevel,
  BitrateAdaptationConfig,
  StreamingBufferConfig,
  StreamingFallbackConfig,
  CDNPerformanceMonitoringConfig,
  CDNMetricsCollectionConfig,
  CDNMetricType,
  CustomCDNMetric,
  CDNPerformanceThresholds,
  CDNAlertingConfig,
  CDNAlertRule,
  CDNAlertSuppressionRule,
  CDNReportingConfig,
  CDNReportType,
  ReportSchedule,
  CustomCDNReport,
  CDNRealTimeMonitoringConfig,
  CDNAnalyticsConfig,
  CDNDataCollectionConfig,
  CDNAnalysisConfig,
  CDNOptimizationAnalysisConfig,
  CDNAnalyticsReportingConfig,
  CDNAnalyticsIntegrationConfig,
  GoogleAnalyticsIntegration,
  DatadogIntegration,
  NewRelicIntegration,
  CustomAnalyticsIntegration,
  CDNFallbackStrategy,
  CDNFallbackOption,
  CDNPerformanceMetrics,
  EdgePerformanceMetric,
  GeographicMetric,
  CDNOptimizationRecommendation,
  OptimizationImpact,
  OptimizationImplementation,
  OptimizationMetrics,
  CDNHealthStatus,
  CDNComponentHealth,
  EdgeLocationHealth,
  CDNHealthIssue,

  // Story 2.4 Task 3: Predictive Asset Loading Engine
  PredictiveLoadingEngineConfig,
  MachineLearningConfig,
  ModelTrainingConfig,
  FeatureEngineeringConfig,
  BehaviorAnalysisConfig,
  IntelligentPrefetchingConfig,
  PredictiveModelConfig,
  AdaptiveLearningConfig,
  PredictivePerformanceConfig,
  AnalyticsIntegrationConfig,
  AssetPrediction,
  UserBehaviorProfile,
  PracticePattern,
  AssetUsagePattern,
  LearningEvent,
  PrefetchRequest,
  PrefetchResult,
  PrefetchResourceUsage,
  PrefetchPerformance,
  ConfusionMatrix,
  TrainingHistoryEntry,
  AdaptationHistoryEntry,
  ModelPersistenceConfig,
  PredictionThresholds,
  CrossValidationConfig,
  ExerciseProgressionModelConfig,
  AssetDemandModelConfig,
  UserIntentModelConfig,
  SessionLengthModelConfig,
  SkillDevelopmentModelConfig,
  ModelEnsembleConfig,
  FeedbackLoopConfig,
  ModelUpdateStrategy,
  OnlineLearningConfig,
  TransferLearningConfig,
  ContinuousImprovementConfig,
  AdaptivePerformanceThresholds,
  AccuracyMetricsConfig,
  LatencyRequirementsConfig,
  ResourceLimitsConfig,
  OptimizationTargetsConfig,
  PredictiveMonitoringConfig,
  BehaviorPatternIntegrationConfig,
  PracticeSessionIntegrationConfig,
  ProgressAnalysisIntegrationConfig,
  DataExchangeProtocolConfig,

  // Core prediction types and enums
  PredictionPriority,
  PracticePatternType,
  AssetType,
  LearningEventType,
  PatternType,
  FeedbackSource,
  ModelUpdateTrigger,

  // Supporting interfaces
  PredictionContext,
  PredictionTrigger,
  PredictionMetadata,
  LearningCharacteristics,
  UserPreferences,
  SkillProgression,
  SessionCharacteristics,
  PredictiveMetrics,
  AssetAccessSequence,
  ContextualUsage,
  SeasonalTrend,
  CorrelatedAsset,
  LearningEventContext,
  LearningEventAsset,
  LearningOutcome,
  LearningEventFeatures,
  LearningEventLabels,
  PrefetchResourceLimits,
  PrefetchValidationRule,
  PrefetchRequestMetadata,
  PrefetchAssetResult,

  // Extended supporting interfaces
  TimeOfDayPattern,
  DurationPattern,
  IntensityPattern,
  AssetPreferencePattern,
  ProgressionStylePattern,
  PlateauIndicator,
  BreakPattern,
  IntensityProfile,
  FocusPattern,
  PredictionHistoryEntry,
  PrioritizationWeights,
  ResourceAllocationStrategy,
  QuotaManagementConfig,
  ThrottlingConfig,
  NetworkQualityThresholds,
  NetworkQualityRange,
  BackgroundLimits,
  ValidationRule,
  ExpirationHandlingStrategy,
  ModelRetentionPolicy,
  ActionThreshold,
  ContextualThreshold,
  ExerciseProgressionFeatures,
  AssetDemandFeatures,
  UserIntentFeatures,
  IntentCategory,
  SessionLengthFeatures,
  SkillDevelopmentFeatures,
  MasteryThreshold,
  PerformanceThreshold,
  ResourceThreshold,
  AdaptationTrigger,
  DegradationThreshold,
  AccuracyMetric,
  AccuracyAlertThreshold,
  RetrainingTrigger,
  OptimizationConstraint,
  FeedbackAggregationStrategy,
  FeedbackWeightingConfig,
  RewardSignalConfig,
  RewardSignal,
  PenaltySignalConfig,
  PenaltySignal,
  FeedbackValidationConfig,
  UpdateFrequency,
  RollbackStrategy,
  RollbackCriteria,
  ModelVersionControl,
  SourceModelConfig,
  ImprovementMetric,
  ExperimentationConfig,
  ExperimentType,
  ABTestingConfig,
  PerformanceBaselineConfig,

  // Additional Task 3 interfaces
  UserSegment,
  SegmentCriteria,
  SegmentCharacteristics,
  CorrelationMatrix,
  PrefetchStrategy,
  PrefetchStrategyParameters,
  PrefetchCondition,
  PredictiveModelsConfig,
  PerformanceOptimizationConfig,
  ModelPerformanceMetrics,
  AdaptiveLearningMetrics,

  // Story 2.4 Task 4: Professional Audio Sample Management
  AudioSampleManagerConfig,
  AudioSampleMetadata,
  AudioSampleFormat,
  AudioSampleQualityProfile,
  AudioSampleCategory,
  AudioSampleOperationResult,
  AudioSampleLibrary,
  AudioSampleLibraryConfig,
  AudioSampleLibraryStatistics,
  AudioSampleQualityThresholds,
  SampleCacheEntry,
  SampleAnalyticsData,
  SampleAnalyticsConfig,
  SampleQualityThresholds,
  SamplePerformanceThresholds,
  SampleAlertThresholds,
  SamplePlaybackMetrics,
  SampleQualityMetrics,
  SamplePerformanceMetrics,
  SampleUsageMetrics,
  SampleInteractionMetrics,
  AdaptiveAudioStreamingConfig,
  IntelligentSampleCacheConfig,
  BandwidthThresholds,
  LatencyThresholds,
} from './storage/index.js';
