import type { DatabaseExercise as Exercise } from '@bassnotion/contracts';

// Mock exercises with actual note data for testing
export const MOCK_EXERCISES: Exercise[] = [
  {
    id: 'ex-walking-bass-1',
    title: 'Walking Bass Line in C',
    description:
      'Learn a classic walking bass pattern over a I-IV-V progression',
    difficulty: 'beginner',
    duration: 8000,
    bpm: 120,
    key: 'C',
    chord_progression: ['C', 'F', 'G', 'C'],
    notes: [
      // C chord - Walking pattern
      {
        id: 'n1',
        timestamp: 0,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
      {
        id: 'n2',
        timestamp: 500,
        string: 3,
        fret: 5,
        duration: 500,
        note: 'D',
        color: 'green',
      },
      {
        id: 'n3',
        timestamp: 1000,
        string: 2,
        fret: 2,
        duration: 500,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'n4',
        timestamp: 1500,
        string: 2,
        fret: 3,
        duration: 500,
        note: 'F',
        color: 'red',
      },

      // F chord - Walking pattern
      {
        id: 'n5',
        timestamp: 2000,
        string: 2,
        fret: 3,
        duration: 500,
        note: 'F',
        color: 'red',
      },
      {
        id: 'n6',
        timestamp: 2500,
        string: 1,
        fret: 0,
        duration: 500,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n7',
        timestamp: 3000,
        string: 3,
        fret: 0,
        duration: 500,
        note: 'A',
        color: 'orange',
      },
      {
        id: 'n8',
        timestamp: 3500,
        string: 3,
        fret: 2,
        duration: 500,
        note: 'B',
        color: 'pink',
      },

      // G chord - Walking pattern
      {
        id: 'n9',
        timestamp: 4000,
        string: 1,
        fret: 0,
        duration: 500,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n10',
        timestamp: 4500,
        string: 3,
        fret: 0,
        duration: 500,
        note: 'A',
        color: 'orange',
      },
      {
        id: 'n11',
        timestamp: 5000,
        string: 3,
        fret: 2,
        duration: 500,
        note: 'B',
        color: 'pink',
      },
      {
        id: 'n12',
        timestamp: 5500,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },

      // C chord - Resolution
      {
        id: 'n13',
        timestamp: 6000,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
      {
        id: 'n14',
        timestamp: 6500,
        string: 2,
        fret: 2,
        duration: 500,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'n15',
        timestamp: 7000,
        string: 1,
        fret: 0,
        duration: 500,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n16',
        timestamp: 7500,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-major-scale-1',
    title: 'C Major Scale Pattern',
    description: 'Practice the C major scale across the fretboard',
    difficulty: 'beginner',
    duration: 8000,
    bpm: 100,
    key: 'C',
    notes: [
      // Ascending scale
      {
        id: 's1',
        timestamp: 0,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
      {
        id: 's2',
        timestamp: 500,
        string: 3,
        fret: 5,
        duration: 500,
        note: 'D',
        color: 'green',
      },
      {
        id: 's3',
        timestamp: 1000,
        string: 2,
        fret: 2,
        duration: 500,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 's4',
        timestamp: 1500,
        string: 2,
        fret: 3,
        duration: 500,
        note: 'F',
        color: 'red',
      },
      {
        id: 's5',
        timestamp: 2000,
        string: 1,
        fret: 0,
        duration: 500,
        note: 'G',
        color: 'purple',
      },
      {
        id: 's6',
        timestamp: 2500,
        string: 1,
        fret: 2,
        duration: 500,
        note: 'A',
        color: 'orange',
      },
      {
        id: 's7',
        timestamp: 3000,
        string: 1,
        fret: 4,
        duration: 500,
        note: 'B',
        color: 'pink',
      },
      {
        id: 's8',
        timestamp: 3500,
        string: 1,
        fret: 5,
        duration: 500,
        note: 'C',
        color: 'blue',
      },

      // Descending scale
      {
        id: 's9',
        timestamp: 4000,
        string: 1,
        fret: 5,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
      {
        id: 's10',
        timestamp: 4500,
        string: 1,
        fret: 4,
        duration: 500,
        note: 'B',
        color: 'pink',
      },
      {
        id: 's11',
        timestamp: 5000,
        string: 1,
        fret: 2,
        duration: 500,
        note: 'A',
        color: 'orange',
      },
      {
        id: 's12',
        timestamp: 5500,
        string: 1,
        fret: 0,
        duration: 500,
        note: 'G',
        color: 'purple',
      },
      {
        id: 's13',
        timestamp: 6000,
        string: 2,
        fret: 3,
        duration: 500,
        note: 'F',
        color: 'red',
      },
      {
        id: 's14',
        timestamp: 6500,
        string: 2,
        fret: 2,
        duration: 500,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 's15',
        timestamp: 7000,
        string: 3,
        fret: 5,
        duration: 500,
        note: 'D',
        color: 'green',
      },
      {
        id: 's16',
        timestamp: 7500,
        string: 3,
        fret: 3,
        duration: 500,
        note: 'C',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-blues-riff-1',
    title: 'Blues Bass Riff in A',
    description: 'A classic blues bass riff using the A blues scale',
    difficulty: 'intermediate',
    duration: 8000,
    bpm: 90,
    key: 'A',
    notes: [
      // Blues riff pattern
      {
        id: 'b1',
        timestamp: 0,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b2',
        timestamp: 375,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b3',
        timestamp: 750,
        string: 3,
        fret: 3,
        duration: 375,
        note: 'C',
        color: 'red',
      },
      {
        id: 'b4',
        timestamp: 1125,
        string: 3,
        fret: 5,
        duration: 375,
        note: 'D',
        color: 'green',
      },

      {
        id: 'b5',
        timestamp: 1500,
        string: 2,
        fret: 2,
        duration: 375,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b6',
        timestamp: 1875,
        string: 3,
        fret: 5,
        duration: 375,
        note: 'D',
        color: 'green',
      },
      {
        id: 'b7',
        timestamp: 2250,
        string: 3,
        fret: 3,
        duration: 375,
        note: 'C',
        color: 'red',
      },
      {
        id: 'b8',
        timestamp: 2625,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },

      // Repeat with variation
      {
        id: 'b9',
        timestamp: 3000,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b10',
        timestamp: 3375,
        string: 2,
        fret: 0,
        duration: 375,
        note: 'D',
        color: 'green',
      },
      {
        id: 'b11',
        timestamp: 3750,
        string: 2,
        fret: 2,
        duration: 375,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b12',
        timestamp: 4125,
        string: 2,
        fret: 0,
        duration: 375,
        note: 'D',
        color: 'green',
      },

      {
        id: 'b13',
        timestamp: 4500,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b14',
        timestamp: 4875,
        string: 1,
        fret: 0,
        duration: 375,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'b15',
        timestamp: 5250,
        string: 2,
        fret: 2,
        duration: 375,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b16',
        timestamp: 5625,
        string: 3,
        fret: 0,
        duration: 375,
        note: 'A',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-funk-groove-1',
    title: 'Funk Groove Pattern',
    description: 'A syncopated funk bass groove with octaves and ghost notes',
    difficulty: 'advanced',
    duration: 4000,
    bpm: 110,
    key: 'E',
    notes: [
      // Funk groove with syncopation
      {
        id: 'f1',
        timestamp: 0,
        string: 4,
        fret: 0,
        duration: 200,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f2',
        timestamp: 200,
        string: 4,
        fret: 0,
        duration: 100,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f3',
        timestamp: 300,
        string: 2,
        fret: 2,
        duration: 200,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f4',
        timestamp: 500,
        string: 4,
        fret: 0,
        duration: 100,
        note: 'E',
        color: 'blue',
      },

      {
        id: 'f5',
        timestamp: 600,
        string: 3,
        fret: 2,
        duration: 150,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f6',
        timestamp: 750,
        string: 2,
        fret: 0,
        duration: 150,
        note: 'D',
        color: 'yellow',
      },
      {
        id: 'f7',
        timestamp: 900,
        string: 2,
        fret: 2,
        duration: 200,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f8',
        timestamp: 1100,
        string: 4,
        fret: 0,
        duration: 100,
        note: 'E',
        color: 'blue',
      },

      // Second bar
      {
        id: 'f9',
        timestamp: 1200,
        string: 4,
        fret: 0,
        duration: 100,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f10',
        timestamp: 1300,
        string: 3,
        fret: 0,
        duration: 150,
        note: 'A',
        color: 'red',
      },
      {
        id: 'f11',
        timestamp: 1450,
        string: 3,
        fret: 2,
        duration: 150,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f12',
        timestamp: 1600,
        string: 2,
        fret: 0,
        duration: 200,
        note: 'D',
        color: 'yellow',
      },

      {
        id: 'f13',
        timestamp: 1800,
        string: 4,
        fret: 0,
        duration: 200,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f14',
        timestamp: 2000,
        string: 2,
        fret: 2,
        duration: 200,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f15',
        timestamp: 2200,
        string: 3,
        fret: 2,
        duration: 100,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f16',
        timestamp: 2300,
        string: 4,
        fret: 0,
        duration: 100,
        note: 'E',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
