import type {
  Exercise,
  NoteDuration,
  MusicalPosition,
} from '@bassnotion/contracts';

// Mock exercises with actual note data for testing
export const MOCK_EXERCISES: Exercise[] = [
  {
    id: 'ex-walking-bass-1',
    title: 'Walking Bass Line in C',
    description:
      'Learn a classic walking bass pattern over a I-IV-V progression',
    difficulty: 'beginner',
    duration: 8000,
    duration_beats: 16,
    bpm: 120,
    key: 'C',
    timeSignature: { numerator: 4, denominator: 4 },
    chord_progression: ['C', 'F', 'G', 'C'],
    // Professional music timing: each chord lasts 1 measure (4 beats)
    chord_durations: [4, 4, 4, 4], // in beats
    chord_positions: [
      { measure: 1, beat: 1 }, // C starts at measure 1, beat 1
      { measure: 2, beat: 1 }, // F starts at measure 2, beat 1
      { measure: 3, beat: 1 }, // G starts at measure 3, beat 1
      { measure: 4, beat: 1 }, // C starts at measure 4, beat 1
    ],
    notes: [
      // C chord - Walking pattern
      {
        id: 'n1',
        timestamp: 0,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
      {
        id: 'n2',
        timestamp: 500,
        string: 3,
        fret: 5,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },
      {
        id: 'n3',
        timestamp: 1000,
        string: 2,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'n4',
        timestamp: 1500,
        string: 2,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'F',
        color: 'red',
      },

      // F chord - Walking pattern
      {
        id: 'n5',
        timestamp: 2000,
        string: 2,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'F',
        color: 'red',
      },
      {
        id: 'n6',
        timestamp: 2500,
        string: 1,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n7',
        timestamp: 3000,
        string: 3,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'orange',
      },
      {
        id: 'n8',
        timestamp: 3500,
        string: 3,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'B',
        color: 'pink',
      },

      // G chord - Walking pattern
      {
        id: 'n9',
        timestamp: 4000,
        string: 1,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n10',
        timestamp: 4500,
        string: 3,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'orange',
      },
      {
        id: 'n11',
        timestamp: 5000,
        string: 3,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'B',
        color: 'pink',
      },
      {
        id: 'n12',
        timestamp: 5500,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },

      // C chord - Resolution
      {
        id: 'n13',
        timestamp: 6000,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
      {
        id: 'n14',
        timestamp: 6500,
        string: 2,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'n15',
        timestamp: 7000,
        string: 1,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'n16',
        timestamp: 7500,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
    ],
    // Add drum pattern for testing
    drum_pattern: {
      enabled: true,
      pattern: [
        // Pattern: Hi-hats on all eighths, kick on 1 and 5, snare on 3 and 7
        // Bar 1
        { timestamp: 0, type: 'kick', velocity: 0.8 },      // Beat 1
        { timestamp: 0, type: 'hihat', velocity: 0.6 },     // Beat 1
        { timestamp: 250, type: 'hihat', velocity: 0.5 },   // Beat 1.5
        { timestamp: 500, type: 'hihat', velocity: 0.6 },   // Beat 2
        { timestamp: 750, type: 'hihat', velocity: 0.5 },   // Beat 2.5
        { timestamp: 1000, type: 'snare', velocity: 0.7 },  // Beat 3
        { timestamp: 1000, type: 'hihat', velocity: 0.6 },  // Beat 3
        { timestamp: 1250, type: 'hihat', velocity: 0.5 },  // Beat 3.5
        { timestamp: 1500, type: 'hihat', velocity: 0.6 },  // Beat 4
        { timestamp: 1750, type: 'hihat', velocity: 0.5 },  // Beat 4.5
        // Bar 2
        { timestamp: 2000, type: 'kick', velocity: 0.8 },   // Beat 5 (1st of bar 2)
        { timestamp: 2000, type: 'hihat', velocity: 0.6 },  // Beat 5
        { timestamp: 2250, type: 'hihat', velocity: 0.5 },  // Beat 5.5
        { timestamp: 2500, type: 'hihat', velocity: 0.6 },  // Beat 6
        { timestamp: 2750, type: 'hihat', velocity: 0.5 },  // Beat 6.5
        { timestamp: 3000, type: 'snare', velocity: 0.7 },  // Beat 7 (3rd of bar 2)
        { timestamp: 3000, type: 'hihat', velocity: 0.6 },  // Beat 7
        { timestamp: 3250, type: 'hihat', velocity: 0.5 },  // Beat 7.5
        { timestamp: 3500, type: 'hihat', velocity: 0.6 },  // Beat 8
        { timestamp: 3750, type: 'hihat', velocity: 0.5 },  // Beat 8.5
        // Bar 3
        { timestamp: 4000, type: 'kick', velocity: 0.8 },   // Beat 9 (1st of bar 3)
        { timestamp: 4000, type: 'hihat', velocity: 0.6 },  // Beat 9
        { timestamp: 4250, type: 'hihat', velocity: 0.5 },  // Beat 9.5
        { timestamp: 4500, type: 'hihat', velocity: 0.6 },  // Beat 10
        { timestamp: 4750, type: 'hihat', velocity: 0.5 },  // Beat 10.5
        { timestamp: 5000, type: 'snare', velocity: 0.7 },  // Beat 11 (3rd of bar 3)
        { timestamp: 5000, type: 'hihat', velocity: 0.6 },  // Beat 11
        { timestamp: 5250, type: 'hihat', velocity: 0.5 },  // Beat 11.5
        { timestamp: 5500, type: 'hihat', velocity: 0.6 },  // Beat 12
        { timestamp: 5750, type: 'hihat', velocity: 0.5 },  // Beat 12.5
        // Bar 4
        { timestamp: 6000, type: 'kick', velocity: 0.8 },   // Beat 13 (1st of bar 4)
        { timestamp: 6000, type: 'hihat', velocity: 0.6 },  // Beat 13
        { timestamp: 6250, type: 'hihat', velocity: 0.5 },  // Beat 13.5
        { timestamp: 6500, type: 'hihat', velocity: 0.6 },  // Beat 14
        { timestamp: 6750, type: 'hihat', velocity: 0.5 },  // Beat 14.5
        { timestamp: 7000, type: 'snare', velocity: 0.7 },  // Beat 15 (3rd of bar 4)
        { timestamp: 7000, type: 'hihat', velocity: 0.6 },  // Beat 15
        { timestamp: 7250, type: 'hihat', velocity: 0.5 },  // Beat 15.5
        { timestamp: 7500, type: 'crash', velocity: 0.8 },  // Beat 16 (end)
        { timestamp: 7500, type: 'hihat', velocity: 0.6 },  // Beat 16
      ],
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-major-scale-1',
    title: 'C Major Scale Pattern',
    description: 'Practice the C major scale across the fretboard',
    difficulty: 'beginner',
    duration: 8000,
    duration_beats: 16,
    bpm: 100,
    key: 'C',
    timeSignature: { numerator: 4, denominator: 4 },
    notes: [
      // Ascending scale
      {
        id: 's1',
        timestamp: 0,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
      {
        id: 's2',
        timestamp: 500,
        string: 3,
        fret: 5,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },
      {
        id: 's3',
        timestamp: 1000,
        string: 2,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 's4',
        timestamp: 1500,
        string: 2,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'F',
        color: 'red',
      },
      {
        id: 's5',
        timestamp: 2000,
        string: 1,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 's6',
        timestamp: 2500,
        string: 1,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'orange',
      },
      {
        id: 's7',
        timestamp: 3000,
        string: 1,
        fret: 4,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'B',
        color: 'pink',
      },
      {
        id: 's8',
        timestamp: 3500,
        string: 1,
        fret: 5,
        duration: 'quarter' as NoteDuration,
        position: { measure: 2, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },

      // Descending scale
      {
        id: 's9',
        timestamp: 4000,
        string: 1,
        fret: 5,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
      {
        id: 's10',
        timestamp: 4500,
        string: 1,
        fret: 4,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'B',
        color: 'pink',
      },
      {
        id: 's11',
        timestamp: 5000,
        string: 1,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'orange',
      },
      {
        id: 's12',
        timestamp: 5500,
        string: 1,
        fret: 0,
        duration: 'quarter' as NoteDuration,
        position: { measure: 3, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 's13',
        timestamp: 6000,
        string: 2,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'F',
        color: 'red',
      },
      {
        id: 's14',
        timestamp: 6500,
        string: 2,
        fret: 2,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 's15',
        timestamp: 7000,
        string: 3,
        fret: 5,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },
      {
        id: 's16',
        timestamp: 7500,
        string: 3,
        fret: 3,
        duration: 'quarter' as NoteDuration,
        position: { measure: 4, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-blues-riff-1',
    title: 'Blues Bass Riff in A',
    description: 'A classic blues bass riff using the A blues scale',
    difficulty: 'intermediate',
    duration: 8000,
    duration_beats: 16,
    bpm: 90,
    key: 'A',
    timeSignature: { numerator: 4, denominator: 4 },
    notes: [
      // Blues riff pattern
      {
        id: 'b1',
        timestamp: 0,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b2',
        timestamp: 375,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 2 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b3',
        timestamp: 750,
        string: 3,
        fret: 3,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'red',
      },
      {
        id: 'b4',
        timestamp: 1125,
        string: 3,
        fret: 5,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 2 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },

      {
        id: 'b5',
        timestamp: 1500,
        string: 2,
        fret: 2,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b6',
        timestamp: 1875,
        string: 3,
        fret: 5,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 2 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },
      {
        id: 'b7',
        timestamp: 2250,
        string: 3,
        fret: 3,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'C',
        color: 'red',
      },
      {
        id: 'b8',
        timestamp: 2625,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 2 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },

      // Repeat with variation
      {
        id: 'b9',
        timestamp: 3000,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b10',
        timestamp: 3375,
        string: 2,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 2 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },
      {
        id: 'b11',
        timestamp: 3750,
        string: 2,
        fret: 2,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b12',
        timestamp: 4125,
        string: 2,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 2 } as MusicalPosition,
        note: 'D',
        color: 'green',
      },

      {
        id: 'b13',
        timestamp: 4500,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },
      {
        id: 'b14',
        timestamp: 4875,
        string: 1,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 3, subdivision: 2 } as MusicalPosition,
        note: 'G',
        color: 'purple',
      },
      {
        id: 'b15',
        timestamp: 5250,
        string: 2,
        fret: 2,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'yellow',
      },
      {
        id: 'b16',
        timestamp: 5625,
        string: 3,
        fret: 0,
        duration: 'eighth' as NoteDuration,
        position: { measure: 2, beat: 4, subdivision: 2 } as MusicalPosition,
        note: 'A',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ex-funk-groove-1',
    title: 'Funk Groove Pattern',
    description: 'A syncopated funk bass groove with octaves and ghost notes',
    difficulty: 'advanced',
    duration: 4000,
    duration_beats: 8,
    bpm: 110,
    key: 'E',
    timeSignature: { numerator: 4, denominator: 4 },
    notes: [
      // Funk groove with syncopation
      {
        id: 'f1',
        timestamp: 0,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f2',
        timestamp: 200,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 1 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f3',
        timestamp: 300,
        string: 2,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 1, subdivision: 2 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f4',
        timestamp: 500,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },

      {
        id: 'f5',
        timestamp: 600,
        string: 3,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 1 } as MusicalPosition,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f6',
        timestamp: 750,
        string: 2,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 2, subdivision: 2 } as MusicalPosition,
        note: 'D',
        color: 'yellow',
      },
      {
        id: 'f7',
        timestamp: 900,
        string: 2,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f8',
        timestamp: 1100,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 3, subdivision: 2 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },

      // Second bar
      {
        id: 'f9',
        timestamp: 1200,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f10',
        timestamp: 1300,
        string: 3,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 1 } as MusicalPosition,
        note: 'A',
        color: 'red',
      },
      {
        id: 'f11',
        timestamp: 1450,
        string: 3,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 1, beat: 4, subdivision: 2 } as MusicalPosition,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f12',
        timestamp: 1600,
        string: 2,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 0 } as MusicalPosition,
        note: 'D',
        color: 'yellow',
      },

      {
        id: 'f13',
        timestamp: 1800,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 2, beat: 1, subdivision: 2 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f14',
        timestamp: 2000,
        string: 2,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 0 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
      {
        id: 'f15',
        timestamp: 2200,
        string: 3,
        fret: 2,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 2 } as MusicalPosition,
        note: 'B',
        color: 'green',
      },
      {
        id: 'f16',
        timestamp: 2300,
        string: 4,
        fret: 0,
        duration: 'sixteenth' as NoteDuration,
        position: { measure: 2, beat: 2, subdivision: 3 } as MusicalPosition,
        note: 'E',
        color: 'blue',
      },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
